### ISSUE TITLE
Update to Support MailPoet v3

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/mailpoet-paid-memberships-pro-add-on#2]
MailPoet 3 is out now and we should update to support the latest version.

Here is a post from the beta launch: https://www.mailpoet.com/mailpoet-3-beta/

I believe @seb86 may be available to help with the work for contract.

**Comment by seb86** [comment]
Hi @ideadude 

Sorry about not completing the previous update. Stuff got in the way. Just bad timing I guess.

I can be available for some contract work next week if you would like to discuss the details over Skype.

https://calendly.com/sebastiendumont/
