### ISSUE TITLE
Lists in Trash show up on the PMPro MailPoet settings page.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/mailpoet-paid-memberships-pro-add-on#4]
We maybe should hide them from the settings.

Another option is to add a "(trashed)" to the list name there to be more clear.

**Comment by andrewlimaza** [comment]
Here is the method we use, it returns all lists including trashed lists - https://github.com/mailpoet/mailpoet/blob/trunk/doc/api_methods/GetLists.md

I am busy looking into workarounds, such as looping through the list ID's to see if they are trashed or not.
